dist: trusty
sudo: required
language: node_js
node_js:
- "9"
addons:
  chrome: stable
before_install:
- wget https://github.com/jgm/pandoc/releases/download/2.1.3/pandoc-2.1.3-1-amd64.deb
- sudo dpkg -i pandoc-*.deb
